[package]
name = "cargo-quill"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
quill-plugin-format = { git = "https://github.com/feather-rs/feather", branch = "main" }
cargo_metadata = "0.12"
anyhow = "1"
argh = "0.1"
heck = "0.3"